name: Sequential Promotion Pipeline

on:
  push:
    branches:
      - dev

jobs:

  dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - run: echo "Deploying to DEV"

  test:
    runs-on: ubuntu-latest
    needs: dev
    environment: test
    steps:
      - uses: actions/checkout@v3
      - run: echo "Deploying to TEST"

  stg:
    runs-on: ubuntu-latest
    needs: test
    environment: stg
    steps:
      - uses: actions/checkout@v3
      - run: echo "Deploying to STG"

  prod:
    runs-on: ubuntu-latest
    needs: stg
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - run: echo "Deploying to PROD ðŸš€"
